### ISSUE TITLE
Misc TODO

### ISSUE THREAD

**Issue by nbokulich** [caporaso-lab/q2-phylogenomics#10]
Running list of miscellaneous to-do items (current list is from review of https://github.com/caporaso-lab/q2-phylogenomics/pull/7, edit or add new comment for additional items)

- [ ] make dict of default params for each method

- [ ] remove commented-out code blocks

- [ ] add single-end mode for map reads etc

- [ ] dereplicate redundant code between map_*_reads and filter_*

- [x] add unit tests for all _assemble.py methods (see #12)

- [ ] revisit feature table construction method in consensus_sequence

- [ ] add validation for PileUpTSVFormat, GenBankFormat

- [ ] move Bowtie2IndexDirFmt -> DNAFASTAFormat transformer to q2-types

- [ ] add support for GenBank format (see note in plugin_setup.py)

- [ ] ceil_coefficient description could be clearer; maybe specify that this is the max number of non-ACGT characters as a fraction of read length.

- [ ] ceil_coefficient should have a range specified

- [ ] refactor test_assemble.py code to reduce duplication where possible (e.g., the consensus sequence tests)

- [ ] determine if it makes sense to allow overlapping sample ids in the consensus sequence step (i.e., one sample giving rise to multiple different genomes) - currently this is explicitly disallowed
